name: view_py310_231017
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scipy
  - scikit-image
  - jinja2
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - openpyxl
  - jupyter
  - appdirs
# Pandas 2.0  should now be compatible to the code - if not, force to pandas=1.5.3
#  - pandas=1.5.3
# only available on conda-forge
  - moviepy
