name: view_26
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyqt=5
  - qtpy
  - pip
  - scipy
  - scikit-image
  - jinja2
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - openpyxl
  - jupyter
  - appdirs
  - moviepy
  # ensure consistent BLAS/LAPACK stack
  - blas=*=openblas
