name: view_dev_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scipy
  - scikit-image
  - jinja2
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - openpyxl
  - nose
  - ipython
  - jupyter
  - appdirs
# only available on conda-forge
  - moviepy
  - ipdb
  - libstdcxx-ng
