name: view_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scipy
  - scikit-image
  - jinja2
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - openpyxl
  - jupyter
  - appdirs
# Pandas 2.0 is currently not compatible to the code
  - pandas=1.5.3
# only available on conda-forge
  - moviepy
