name: view_26
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pyqt6 != 6.6.1
  - qtpy
  - pip
  - scipy
  - scikit-image
  - numpy>=2
  - jinja2
  - seaborn
  - bokeh
  - xlrd
  - pyqtgraph
  - whoosh
  - openpyxl
  - jupyter
  - appdirs
  # only available on conda-forge
  - moviepy<2
  # ensure consistent BLAS/LAPACK stack
  - blas=*=openblas
