"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import napari

import pandas as pd
from PyQt5.QtCore import pyqtSignal

from PyQt5.QtWidgets import QVBoxLayout, QGroupBox, QTabWidget
from matplotlib import pyplot as plt

from view.gui.central_widget import CentralWidget
from view.gui.loader_widgets import LogLoadWidget, ListLoadWidget

from view.gui.data_manager import DataManager
from view.gui.direct_load import DirectDataLoader
from view.gui.logger import LoggerGroupBox
from view.gui.main_function_widgets import MainFunctionAbstract



class NapariPyViewWidget(CentralWidget):
    export_data_signal = pyqtSignal(list, list, pd.DataFrame, int, tuple, tuple, int, name="export data")
    reset_iltis_signal = pyqtSignal(name="reset ILTIS")

    def __init__(self, parent, napari_viewer: "napari.viewer.Viewer"):
        super().__init__(parent)
        self.napari_viewer = napari_viewer

        self.init_flags()
        self.current_measurement_label = None
        self.init_ui()
        self.measurement_list = None
        self.yml_file = None

        plt.ion()

    def init_ui(self):
        # Create a single VBox layout for the main widget
        main_vbox = QVBoxLayout(self)

        # Instantiate the calcMethod_box
        calcMethod_flags = ["LE_CalcMethod"]
        self.calcMethod_box = MainFunctionAbstract(
            parent=self, button_names={},
            flag_names=calcMethod_flags,
            flag_defaults=[self.flags[f] for f in calcMethod_flags],
            group_name="Choose the method for calculating signals "
                       "(does not affect raw data loading and artifact correction)"
        )
        self.calcMethod_box.flag_update_signal.connect(self.flag_update_request_gui)
        self.main_function_widgets["calc method choice box"] = self.calcMethod_box
        main_vbox.addWidget(self.calcMethod_box)

        # Instantiate loader_tabs
        loader_tabs = QTabWidget(self)
        main_vbox.addWidget(loader_tabs)

        direct_loader = DirectDataLoader(self, self.setup_choice_box.get_current_LE_loadExp())
        direct_loader.data_loaded_signal.connect(self.direct_load_finalize)
        self.setup_choice_box.return_LE_loadExp.connect(direct_loader.refresh_layout)
        loader_tabs.addTab(direct_loader, "Direct load from raw file (no pre-requirements)")

        log_load_widget = LogLoadWidget(self)
        log_load_widget.new_vws_log_load.clicked.connect(self.load_from_new_vws_log)
        log_load_widget.choose_from_current_vws_log.clicked.connect(self.choose_row_from_current_vws_log)
        loader_tabs.addTab(log_load_widget, "Direct load from log file (no pre-requirements)")

        list_load_widget = ListLoadWidget(self)
        list_load_widget.new_load.clicked.connect(self.load_from_new_list)
        list_load_widget.choose_from_current_list.clicked.connect(self.choose_row_from_current_list)
        list_load_widget.new_vws_log_load.clicked.connect(self.load_from_new_vws_log)
        list_load_widget.choose_from_current_vws_log.clicked.connect(self.choose_row_from_current_vws_log)
        list_load_widget.yaml_loader.return_filename_signal.connect(self.load_yml_flags)
        list_load_widget.quick_load_from_current_lst_box.send_data.connect(self.quick_load_from_current_lst)
        list_load_widget.quick_load_from_current_lst_box.flag_update_signal.connect(self.flag_update_request_gui)
        self.main_function_widgets["load_lst"] = list_load_widget.new_load
        self.main_function_widgets["select row from current list"] = list_load_widget.choose_from_current_list
        self.main_function_widgets["select row from new vws log file"] = list_load_widget.new_vws_log_load
        self.main_function_widgets[
            "select row from current vws log file"] = list_load_widget.choose_from_current_vws_log
        self.main_function_widgets["quick load from current list"] = list_load_widget.quick_load_from_current_lst_box
        self.main_function_widgets["selected list file"] = list_load_widget.selected_list_file_box
        self.current_measurement_label = list_load_widget.current_measurement_label
        loader_tabs.addTab(list_load_widget, "List load (pre-requirements: YML File, folder structure, "
                                             "measurement list files)")

        # Instantiate data_manager_group_box
        data_manager_group_box = QGroupBox("Data Manager")
        data_manager_vbox = QVBoxLayout(data_manager_group_box)

        flags_values2use = \
            ["LE_loadExp", "LE_CalcMethod", "STG_ReportTag", "STG_Measu"] + self.flags.compound_path_flags

        def temp(x):
            return lambda p1: p1.metadata.get(x, "N/A")

        flags_values2use_dict = {k: k for k in flags_values2use}
        p1_values2use = {
            "Component\nOdors": temp("odor"), "Stimulus": temp("stimulus"), "Stimulus\nConcentration": temp("odor_nr"),
            "No. of pulses in stimuli": lambda p1: p1.metadata["pulsed_stimuli_handler"].stimulus_frame.shape[0],
            "Stimulus pulse start times\nrelative to imaging start (s)":
                lambda p1: [x / pd.Timedelta(seconds=1)
                            for x in p1.metadata["pulsed_stimuli_handler"].get_pulse_start_times()],
            "Stimulus pulse end times\nrelative to imaging start (s)":
                lambda p1: [x / pd.Timedelta(seconds=1)
                            for x in p1.metadata["pulsed_stimuli_handler"].get_pulse_end_times()],
            "Measurement\nLabel": temp("ex_name"), "Raw File Name": temp("full_raw_data_path_str"),
            "No. of frames": temp("frames"),
            "Frames per second": lambda p1: p1.metadata.frequency,
            "No. of Pixels along X": temp("format_x"),
            "No. of Pixels along Y": temp("format_y"),
        }

        self.data_manager = DataManager(
            parent=self, flag_values_to_use=flags_values2use_dict, p1_values_to_use=p1_values2use, label_joiner="_",
            default_label_cols=["STG_Measu", "STG_ReportTag"],
            precedence_order=[
                "STG_ReportTag", "STG_Measu", "Measurement\nLabel",
                "Stimulus", "Stimulus\nConcentration", "Component\nOdors",
                "No. of pulses in stimuli", "Stimulus pulse start times\nrelative to imaging start (s)",
                "Stimulus pulse end times\nrelative to imaging start (s)",
                "No. of frames", "Frames per second", "No. of Pixels along X", "No. of Pixels along Y",
                "LE_loadExp", "LE_CalcMethod"]
        )
        self.data_manager.remove_data_signal.connect(self.remove_data)
        data_manager_vbox.addWidget(self.data_manager.ui_table)

        main_vbox.addWidget(data_manager_group_box)

        # Instantiate log_pte
        self.log_pte = LoggerGroupBox(self)
        main_vbox.addWidget(self.log_pte)

        # Disable all actions other than YML loader
        self.enable_disable_functions_all(
            enable=False, main_exceptions=["yml loader", "setup choice box", "calc method choice box"])
